### PR TITLE
Attempt to retrieve the API key from GCE metadata if not present or the default value in the config files was left unedited.

### PR DESCRIPTION
**Pull request by igorpeshansky**

### CODE REVIEW

**Comment by ekilby** [comment]
So if the value is left as "STACKDRIVER_API_KEY" (literal) it will look it up?

I think it would be better to have an explicit "try to detect" case like we do with the instance ids, that way we can hard-set them when debugging configs and then switch them over to detect.

**Comment by igorpeshansky** [comment]
Correct. The idea is that we can reuse the existing configs without creating a combinatorial explosion of boolean options.
We can still hard-set them when debugging configs -- any value but "STACKDRIVER_API_KEY" will be used verbatim.
Am I missing something?

**Comment by ekilby** [comment]
I just don't think that value is very clear, and if a literal value is going to trigger a special case I'd rather have it look like it will "DETECT_FROM_METADATA" or some such.

**Comment by igorpeshansky** [comment]
Sure, I can change it to "DETECT_FROM_METADATA", but that would require the users to either edit the config anyway after downloading it (something I think we want to avoid) or pull from a different config directory (adding more sets of configs for us to maintain). Should I go with the latter option and add another set of directory trees to jmxtrans-config-stackdriver?

**Comment by ekilby** [comment]
To avoid proliferation, let's just go with the default value.  It will be a user education thing I guess, which it was going to be anyway.

**Comment by igorpeshansky** [comment]
Thanks. So, is this ready to merge?

**Comment by ekilby** [comment]
Yes, if it has been tested successfully in both states (special value and valid API key).

**Comment by igorpeshansky** [comment]
Just tested with and without the API key in the (Cassandra) config. The data was sent to GCM and displayed. I can haz LGTM?

**Comment by igorpeshansky** [comment]
On second thought, also changed it to get the key from metadata if it wasn't present in the config at all. PTAL.

**Comment by ekilby** [comment]
LGTM.

**Comment by igorpeshansky** [comment]
Thanks, merged.

**Pull request merged**
